# Generated by Django 3.2.7 on 2021-10-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='name',
        ),
        migrations.AddField(
            model_name='quantity',
            name='amount',
            field=models.PositiveIntegerField(default=None, unique=True, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
