# Generated by Django 3.2.7 on 2021-10-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_owner'),
        ('recipes', '0005_recipe_user'),
    ]

    operations = [
    ]
